selector:
  type: ['PosteriorBasedSelector']
  model_name: 'Coteaching'
  model_config_path: 'DataSelection/configs/models/cifar10h/resnet_co_teaching.yaml'
  burnout_period: 50    
tensorboard:
  save_events: False
