device: cuda
cudnn:
  benchmark: True
  deterministic: True
dataset:
  name: NoisyKaggle
  dataset_dir: /datadrive/rsna_train
  n_channels: 3
  n_classes: 2
model:
  type: rsna
  name: densenet121
train:
  pretrained: False
  seed: 0
  batch_size: 32
  optimizer: adam
  base_lr: 0.0001
  output_dir: rsna/densenet121/scratch/vanilla
  log_period: 5
  checkpoint_period: 2
  dataloader:
    num_workers: 3
    drop_last: False
    pin_memory: False
validation:
  batch_size: 32
  dataloader:
    num_workers: 2
    drop_last: False
    pin_memory: False
scheduler:
  epochs: 50
  type: multistep
  milestones: [10, 25]
  lr_decay: 0.5
preprocess:
  center_crop_size: 224
  resize: 256
augmentation:
  use_random_horizontal_flip: True
  use_random_affine: True
  use_random_color: True
  use_random_crop: True
  use_gamma_transform: False
  use_random_erasing: False
  add_gaussian_noise: False
  random_horizontal_flip:
    prob: 0.5
  random_erasing:
      scale: (0.005, 0.04)
      ratio: (0.5, 2)
  random_affine:
    max_angle: 15
    max_horizontal_shift: 0.00
    max_vertical_shift: 0.00
    max_shear: 5
  random_color:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.0
  random_crop:
      scale: (0.8, 1.0)

  
  
  


