device: cuda
cudnn:
  benchmark: True
  deterministic: True
dataset:
  name: NoisyKaggle
  dataset_dir: /datadrive/rsna_train
  n_channels: 3
  n_classes: 2
train:
  pretrained: False
  seed: 1
  
  batch_size: 32
  optimizer: adam
  base_lr: 0.0001
  output_dir: rsna/ssup_tanh04_reg_aug
  tanh_regularisation: 0.40
  use_self_supervision: True
  self_supervision:
    checkpoints: ["logs/kaggle/self_supervised/lightning_logs/simclr_seed_3/checkpoints/last.ckpt"]
  use_co_teaching: False
  log_period: 5
  checkpoint_period: 5
  
  dataloader:
    num_workers: 4
    drop_last: False
    pin_memory: False
validation:
  batch_size: 32
  dataloader:
    num_workers: 4
    drop_last: False
    pin_memory: False
scheduler:
  epochs: 30
  type: multistep
  milestones: [20]
  lr_decay: 0.1
preprocess:
  center_crop_size: 224
  resize: 256
augmentation:
  use_random_horizontal_flip: True
  use_random_affine: True
  use_random_color: True
  use_random_crop: True
  use_gamma_transform: False
  use_random_erasing: False
  add_gaussian_noise: False
  random_horizontal_flip:
    prob: 0.5
  random_affine:
    max_angle: 30
    max_horizontal_shift: 0.00
    max_vertical_shift: 0.00
    max_shear: 10
  random_color:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.0
  random_crop:
      scale: (0.8, 1.0)

  
  
  


