selector:
  type: ['PosteriorBasedSelector']
  model_name: 'Vanilla'
  model_config_path: 'DataSelection/configs/models/rsna/densenet121_scratch.yaml'
  burnout_period: 15
tensorboard:
  save_events: False