selector:
  type: ['PosteriorBasedSelector']
  model_name: 'Coteaching-EMA-SSUP-graph'
  model_config_path: 'DataSelection/configs/models/rsna/densenet121_scratch_coteaching_ema_graph.yaml'
  burnout_period: 15
tensorboard:
  save_events: False