device: cuda:2
cudnn:
  benchmark: True
  deterministic: True
dataset:
  name: COVID
  dataset_dir: /datadrive/uhb
  n_channels: 3
  n_classes: 2
train:
  pretrained: False
  resume_epoch: 0
  seed: 1
  
  batch_size: 32
  optimizer: adam
  base_lr: 0.001
  output_dir: experiments/covid/self_supervised_freeze
  use_self_supervision: True
  self_supervision:
    checkpoints: ["kaggle/self_supervision_v3/lightning_logs/SimCLR_seed_3/checkpoints/last.ckpt"]
  use_co_teaching: False
  log_period: 5
  checkpoint_period: 5
  
  dataloader:
    num_workers: 4
    drop_last: False
    pin_memory: False
validation:
  batch_size: 32
  dataloader:
    num_workers: 4
    drop_last: False
    pin_memory: False
scheduler:
  epochs: 40
  type: multistep
  milestones: [20]
  lr_decay: 0.1
preprocess:
  center_crop_size: 224
  resize: 256
augmentation:
  use_random_horizontal_flip: False
  use_random_affine: False
  use_random_color: False
  use_random_crop: False
  use_gamma_transform: False
  use_random_erasing: False
  add_gaussian_noise: False
  random_horizontal_flip:
    prob: 0.5
  random_erasing:
      scale: (0.005, 0.04)
      ratio: (0.5, 2)
  random_affine:
    max_angle: 180
    max_horizontal_shift: 0.00
    max_vertical_shift: 0.00
    max_shear: 10
  random_color:
    brightness: 0.3
    contrast: 0.3
    saturation: 0.0
  random_crop:
      scale: (0.8, 1.0)

  
  
  


