device: cuda
cudnn:
  benchmark: True
  deterministic: True
dataset:
  name: COVID
  dataset_dir: /datadrive/uhb
  n_channels: 3
  n_classes: 2
model:
  type: rsna
  name: densenet121
train:
  resume_epoch: 0
  pretrained: False
  seed: 0
  
  batch_size: 32
  optimizer: adam
  base_lr: 0.001
  output_dir: experiments/covid/scratch/vanilla
  use_co_teaching: False
  co_teaching_forget_rate: 0.10
  co_teaching_num_warmup: 3
  log_period: 5
  checkpoint_period: 5
  
  dataloader:
    num_workers: 6
    drop_last: False
    pin_memory: False
validation:
  batch_size: 32
  dataloader:
    num_workers: 6
    drop_last: False
    pin_memory: False
scheduler:
  epochs: 50
  type: multistep
  milestones: [25]
  lr_decay: 0.1
preprocess:
  center_crop_size: 224
  resize: 256
augmentation:
  use_random_horizontal_flip: True
  use_random_affine: True
  use_random_color: True
  use_random_crop: True
  use_gamma_transform: False
  use_random_erasing: False
  add_gaussian_noise: False
  random_horizontal_flip:
    prob: 0.5
  random_affine:
    max_angle: 15
    max_horizontal_shift: 0.00
    max_vertical_shift: 0.00
    max_shear: 5
  random_color:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.0
  random_crop:
      scale: (0.8, 1.0)

  
  
  


