device: cuda:3
cudnn:
  benchmark: True
  deterministic: True
dataset:
  name: Kaggle
  dataset_dir: /datadrive/rsna_train
  n_channels: 3
  n_classes: 2
model:
  type: rsna
  name: densenet121
train:
  pretrained: False
  resume_epoch: 0
  seed: 3
  
  batch_size: 32
  optimizer: adam
  base_lr: 0.0001
  output_dir: experiments/kaggle/scratch
  use_co_teaching: False
  log_period: 5
  checkpoint_period: 5
  
  dataloader:
    num_workers: 4
    drop_last: False
    pin_memory: False
validation:
  batch_size: 32
  dataloader:
    num_workers: 4
    drop_last: False
    pin_memory: False
scheduler:
  epochs: 75
  type: multistep
  milestones: [25, 50]
  lr_decay: 0.1
preprocess:
  center_crop_size: 224
  resize: 256
augmentation:
  use_random_horizontal_flip: True
  use_random_affine: True
  use_random_color: True
  use_random_crop: True
  use_gamma_transform: False
  use_random_erasing: False
  add_gaussian_noise: False
  use_elastic_transform: False
  random_horizontal_flip:
    prob: 0.5
  random_erasing:
      scale: (0.005, 0.04)
      ratio: (0.5, 2)
  random_affine:
    max_angle: 15
    max_horizontal_shift: 0.00
    max_vertical_shift: 0.00
    max_shear: 5
  random_color:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.0
  random_crop:
      scale: (0.8, 1.0)

  
  
  


